import type { StaticIcon, StaticColor, PaymentMethod, Category } from './types'

export const STATIC_ICONS: StaticIcon[] = [
  { id_icon: 'IC-001',  icon_base: 'fa-solid fa-utensils' },
  { id_icon: 'IC-002',  icon_base: 'fa-solid fa-bag-shopping' },
  { id_icon: 'IC-003',  icon_base: 'fa-solid fa-ticket' },
  { id_icon: 'IC-004',  icon_base: 'fa-solid fa-square-parking' },
  { id_icon: 'IC-005',  icon_base: 'fa-solid fa-gas-pump' },
  { id_icon: 'IC-006',  icon_base: 'fa-solid fa-briefcase' },
  { id_icon: 'IC-007',  icon_base: 'fa-solid fa-arrow-trend-up' },
  { id_icon: 'IC-008',  icon_base: 'fa-solid fa-building' },
  { id_icon: 'IC-009',  icon_base: 'fa-solid fa-shuffle' },
  { id_icon: 'IC-010',  icon_base: 'fa-solid fa-arrows-rotate' },
  { id_icon: 'IC-011',  icon_base: 'fa-solid fa-heart-pulse' },
  { id_icon: 'IC-012',  icon_base: 'fa-solid fa-bolt' },
  { id_icon: 'IC-013',  icon_base: 'fa-solid fa-money-bill-transfer' },
  { id_icon: 'IC-014',  icon_base: 'fa-solid fa-hand-holding-dollar' },
  { id_icon: 'IC-015',  icon_base: 'fa-solid fa-house' },
  { id_icon: 'IC-016',  icon_base: 'fa-solid fa-paw' },
  { id_icon: 'IC-017',  icon_base: 'fa-solid fa-graduation-cap' },
  { id_icon: 'IC-018',  icon_base: 'fa-solid fa-plane' },
  { id_icon: 'IC-019',  icon_base: 'fa-solid fa-gift' },
  { id_icon: 'IC-020',  icon_base: 'fa-solid fa-scissors' },
  { id_icon: 'IC-021',  icon_base: 'fa-solid fa-dumbbell' },
  { id_icon: 'IC-022',  icon_base: 'fa-solid fa-bus' },
  { id_icon: 'IC-023',  icon_base: 'fa-solid fa-heart' },
  { id_icon: 'IC-024',  icon_base: 'fa-solid fa-piggy-bank' },
  { id_icon: 'IC-025',  icon_base: 'fa-solid fa-droplet' },
  { id_icon: 'IC-026',  icon_base: 'fa-solid fa-wrench' },
  { id_icon: 'IC-027',  icon_base: 'fa-solid fa-music' },
  { id_icon: 'IC-APPLE', icon_base: 'fa-brands fa-apple' },
  { id_icon: 'IC-028',  icon_base: 'fa-brands fa-xbox' },
  { id_icon: 'IC-029',  icon_base: 'fa-solid fa-tv' },
  { id_icon: 'IC-030',  icon_base: 'fa-solid fa-chess-knight' },
  { id_icon: 'IC-031',  icon_base: 'fa-brands fa-playstation' },
  { id_icon: 'IC-032',  icon_base: 'fa-solid fa-mug-hot' },
  { id_icon: 'IC-033',  icon_base: 'fa-solid fa-shirt' },
  { id_icon: 'IC-035',  icon_base: 'fa-solid fa-pills' },
  { id_icon: 'IC-036',  icon_base: 'fa-solid fa-stethoscope' },
  { id_icon: 'IC-038',  icon_base: 'fa-solid fa-motorcycle' },
  { id_icon: 'IC-039',  icon_base: 'fa-solid fa-plane-departure' },
  { id_icon: 'IC-041',  icon_base: 'fa-solid fa-wifi' },
  { id_icon: 'IC-042',  icon_base: 'fa-solid fa-laptop' },
  { id_icon: 'IC-043',  icon_base: 'fa-solid fa-mobile-screen' },
  { id_icon: 'IC-044',  icon_base: 'fa-solid fa-couch' },
  { id_icon: 'IC-045',  icon_base: 'fa-solid fa-bed' },
  { id_icon: 'IC-046',  icon_base: 'fa-solid fa-baby-carriage' },
  { id_icon: 'IC-047',  icon_base: 'fa-solid fa-broom' },
  { id_icon: 'IC-048',  icon_base: 'fa-solid fa-brush' },
  { id_icon: 'IC-049',  icon_base: 'fa-solid fa-hammer' },
  { id_icon: 'IC-050',  icon_base: 'fa-solid fa-wine-glass' },
  { id_icon: 'IC-051',  icon_base: 'fa-solid fa-book' },
  { id_icon: 'IC-052',  icon_base: 'fa-solid fa-beer-mug-empty' },
  { id_icon: 'IC-053',  icon_base: 'fa-solid fa-cart-shopping' },
  { id_icon: 'IC-054',  icon_base: 'fa-solid fa-gem' },
  { id_icon: 'IC-055',  icon_base: 'fa-solid fa-candy-cane' },
  { id_icon: 'IC-056',  icon_base: 'fa-solid fa-car' },
  { id_icon: 'IC-AUDIT',icon_base: 'fa-solid fa-magnifying-glass-dollar' },
]

export const STATIC_COLORS: StaticColor[] = [
  { id_color: 'COL-01', hex: '#3b82f6', tailwind: 'text-blue-500',     bg: 'bg-blue-500/20' },
  { id_color: 'COL-02', hex: '#10b981', tailwind: 'text-emerald-500',  bg: 'bg-emerald-500/20' },
  { id_color: 'COL-03', hex: '#f59e0b', tailwind: 'text-amber-500',    bg: 'bg-amber-500/20' },
  { id_color: 'COL-04', hex: '#f43f5e', tailwind: 'text-rose-500',     bg: 'bg-rose-500/20' },
  { id_color: 'COL-05', hex: '#a855f7', tailwind: 'text-purple-500',   bg: 'bg-purple-500/20' },
  { id_color: 'COL-06', hex: '#06b6d4', tailwind: 'text-cyan-500',     bg: 'bg-cyan-500/20' },
  { id_color: 'COL-07', hex: '#64748b', tailwind: 'text-slate-500',    bg: 'bg-slate-500/20' },
  { id_color: 'COL-08', hex: '#f97316', tailwind: 'text-orange-500',   bg: 'bg-orange-500/20' },
  { id_color: 'COL-09', hex: '#6366f1', tailwind: 'text-indigo-500',   bg: 'bg-indigo-500/20' },
  { id_color: 'COL-10', hex: '#ec4899', tailwind: 'text-pink-500',     bg: 'bg-pink-500/20' },
  { id_color: 'COL-11', hex: '#1e3a8a', tailwind: 'text-blue-900',     bg: 'bg-blue-900/20' },
  { id_color: 'COL-12', hex: '#14532d', tailwind: 'text-green-900',    bg: 'bg-green-900/20' },
  { id_color: 'COL-13', hex: '#9ca3af', tailwind: 'text-gray-400',     bg: 'bg-gray-400/20' },
  { id_color: 'COL-14', hex: '#7f1d1d', tailwind: 'text-red-900',      bg: 'bg-red-900/20' },
  { id_color: 'COL-15', hex: '#14b8a6', tailwind: 'text-teal-500',     bg: 'bg-teal-500/20' },
  { id_color: 'COL-16', hex: '#84cc16', tailwind: 'text-lime-500',     bg: 'bg-lime-500/20' },
  { id_color: 'COL-17', hex: '#d946ef', tailwind: 'text-fuchsia-500',  bg: 'bg-fuchsia-500/20' },
  { id_color: 'COL-18', hex: '#8b5cf6', tailwind: 'text-violet-500',   bg: 'bg-violet-500/20' },
  { id_color: 'COL-19', hex: '#0ea5e9', tailwind: 'text-sky-500',      bg: 'bg-sky-500/20' },
  { id_color: 'COL-20', hex: '#facc15', tailwind: 'text-yellow-400',   bg: 'bg-yellow-400/20' },
  { id_color: 'COL-21', hex: '#71717a', tailwind: 'text-zinc-500',     bg: 'bg-zinc-500/20' },
  { id_color: 'COL-22', hex: '#78716c', tailwind: 'text-stone-500',    bg: 'bg-stone-500/20' },
  { id_color: 'COL-23', hex: '#ef4444', tailwind: 'text-red-500',      bg: 'bg-red-500/20' },
  { id_color: 'COL-24', hex: '#9a3412', tailwind: 'text-orange-800',   bg: 'bg-orange-800/20' },
  { id_color: 'COL-28', hex: '#1e1b4b', tailwind: 'text-indigo-950',   bg: 'bg-indigo-950/30' },
  { id_color: 'COL-29', hex: '#78350f', tailwind: 'text-amber-900',    bg: 'bg-amber-900/20' },
  { id_color: 'COL-30', hex: '#be185d', tailwind: 'text-pink-700',     bg: 'bg-pink-700/20' },
]

export const PAYMENT_METHODS: PaymentMethod[] = [
  { id_metodo_pago: 'MP-EFECTIVO', nombre: 'Efectivo',        icon: 'fa-solid fa-money-bill-1-wave', id_color: 'COL-02' },
  { id_metodo_pago: 'MP-TDD',      nombre: 'Tarjeta Débito',  icon: 'fa-solid fa-credit-card',       id_color: 'COL-01' },
  { id_metodo_pago: 'MP-TDC',      nombre: 'Tarjeta Crédito', icon: 'fa-regular fa-credit-card',     id_color: 'COL-05' },
]

export const DEFAULT_CATEGORIES: Omit<Category, 'created_at' | 'updated_at'>[] = [
  { id: 'CAT-DEF-FOOD',  user_id: null, name: 'Alimentos y bebidas', icon_id: 'IC-001', color_id: 'COL-08', is_default: true, sort_order: 1 },
  { id: 'CAT-DEF-SHOP',  user_id: null, name: 'Compras',             icon_id: 'IC-002', color_id: 'COL-19', is_default: true, sort_order: 2 },
  { id: 'CAT-DEF-ENT',   user_id: null, name: 'Entretenimiento',     icon_id: 'IC-003', color_id: 'COL-10', is_default: true, sort_order: 3 },
  { id: 'CAT-DEF-GAS',   user_id: null, name: 'Gasolina',            icon_id: 'IC-005', color_id: 'COL-14', is_default: true, sort_order: 4 },
  { id: 'CAT-DEF-HOME',  user_id: null, name: 'Hogar',               icon_id: 'IC-015', color_id: 'COL-24', is_default: true, sort_order: 5 },
  { id: 'CAT-DEF-SAL',   user_id: null, name: 'Salud',               icon_id: 'IC-011', color_id: 'COL-06', is_default: true, sort_order: 6 },
  { id: 'CAT-DEF-SERV',  user_id: null, name: 'Servicios',           icon_id: 'IC-026', color_id: 'COL-20', is_default: true, sort_order: 7 },
  { id: 'CAT-DEF-REC',   user_id: null, name: 'Recurrente',          icon_id: 'IC-010', color_id: 'COL-03', is_default: true, sort_order: 8 },
  { id: 'CAT-DEF-TRANS', user_id: null, name: 'Transporte',          icon_id: 'IC-022', color_id: 'COL-01', is_default: true, sort_order: 9 },
  { id: 'CAT-DEF-INV',   user_id: null, name: 'Inversiones',         icon_id: 'IC-007', color_id: 'COL-09', is_default: true, sort_order: 10 },
  { id: 'CAT-DEF-HON',   user_id: null, name: 'Honorarios',          icon_id: 'IC-006', color_id: 'COL-22', is_default: true, sort_order: 11 },
  { id: 'CAT-DEF-AMOR',  user_id: null, name: 'Amor',                icon_id: 'IC-023', color_id: 'COL-23', is_default: true, sort_order: 12 },
  { id: 'CAT-DEF-VENT',  user_id: null, name: 'Ventas y Negocios',   icon_id: 'IC-014', color_id: 'COL-12', is_default: true, sort_order: 13 },
  { id: 'CAT-DEF-EST',   user_id: null, name: 'Estacionamiento',     icon_id: 'IC-004', color_id: 'COL-05', is_default: true, sort_order: 14 },
  { id: 'CAT-DEF-OTHER', user_id: null, name: 'Otro',                icon_id: 'IC-009', color_id: 'COL-21', is_default: true, sort_order: 15 },
  { id: 'CAT-AUDIT',     user_id: null, name: 'Ajuste',              icon_id: 'IC-AUDIT', color_id: 'COL-30', is_default: true, sort_order: 99 },
  { id: 'CAT-APPLE',    user_id: null, name: 'Apple Pay',           icon_id: 'IC-APPLE', color_id: 'COL-01', is_default: true, sort_order: 98 },
]

export const TRANSACTION_TYPES = {
  'TR-GASTO':    { label: 'Gasto',         color: 'text-rose-400',    bg: 'bg-rose-500/10' },
  'TR-INGRESO':  { label: 'Ingreso',        color: 'text-emerald-400', bg: 'bg-emerald-500/10' },
  'TR-TRANSFER': { label: 'Transferencia',  color: 'text-sky-400',     bg: 'bg-sky-500/10' },
} as const

export const MONTHS_ES = [
  'Enero','Febrero','Marzo','Abril','Mayo','Junio',
  'Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre',
]

export const SUPPORTED_CURRENCIES: { code: string; name: string; symbol: string; autoRate?: boolean }[] = [
  // ── Base ──────────────────────────────────────────────────────────────────
  { code: 'MXN', name: 'Peso mexicano',                    symbol: '$',      autoRate: false },
  // ── Más usadas ────────────────────────────────────────────────────────────
  { code: 'USD', name: 'Dólar estadounidense',             symbol: '$',      autoRate: true },
  { code: 'EUR', name: 'Euro',                             symbol: '€',      autoRate: true },
  { code: 'GBP', name: 'Libra esterlina',                  symbol: '£',      autoRate: true },
  { code: 'CAD', name: 'Dólar canadiense',                 symbol: 'C$',     autoRate: true },
  { code: 'AUD', name: 'Dólar australiano',                symbol: 'A$',     autoRate: true },
  { code: 'JPY', name: 'Yen japonés',                      symbol: '¥',      autoRate: true },
  { code: 'CHF', name: 'Franco suizo',                     symbol: 'CHF',    autoRate: true },
  // ── Latinoamérica ─────────────────────────────────────────────────────────
  { code: 'ARS', name: 'Peso argentino',                   symbol: '$',      autoRate: true },
  { code: 'BOB', name: 'Boliviano',                        symbol: 'Bs.',    autoRate: true },
  { code: 'BRL', name: 'Real brasileño',                   symbol: 'R$',     autoRate: true },
  { code: 'BZD', name: 'Dólar de Belice',                  symbol: '$',      autoRate: true },
  { code: 'CLP', name: 'Peso chileno',                     symbol: '$',      autoRate: true },
  { code: 'COP', name: 'Peso colombiano',                  symbol: '$',      autoRate: true },
  { code: 'CRC', name: 'Colón costarricense',              symbol: '₡',      autoRate: true },
  { code: 'CUP', name: 'Peso cubano',                      symbol: '$',      autoRate: true },
  { code: 'DOP', name: 'Peso dominicano',                  symbol: '$',      autoRate: true },
  { code: 'GTQ', name: 'Quetzal guatemalteco',             symbol: 'Q',      autoRate: true },
  { code: 'GYD', name: 'Dólar guyanés',                    symbol: '$',      autoRate: true },
  { code: 'HNL', name: 'Lempira hondureño',                symbol: 'L',      autoRate: true },
  { code: 'HTG', name: 'Gourde haitiano',                  symbol: 'G',      autoRate: true },
  { code: 'JMD', name: 'Dólar jamaicano',                  symbol: '$',      autoRate: true },
  { code: 'NIO', name: 'Córdoba nicaragüense',             symbol: 'C$',     autoRate: true },
  { code: 'PAB', name: 'Balboa panameño',                  symbol: 'B/.',    autoRate: true },
  { code: 'PEN', name: 'Sol peruano',                      symbol: 'S/',     autoRate: true },
  { code: 'PYG', name: 'Guaraní paraguayo',                symbol: '₲',      autoRate: true },
  { code: 'SRD', name: 'Dólar surinamés',                  symbol: '$',      autoRate: true },
  { code: 'SVC', name: 'Colón salvadoreño',                symbol: '₡',      autoRate: true },
  { code: 'TTD', name: 'Dólar de Trinidad y Tobago',       symbol: '$',      autoRate: true },
  { code: 'UYU', name: 'Peso uruguayo',                    symbol: '$U',     autoRate: true },
  { code: 'VES', name: 'Bolívar venezolano',               symbol: 'Bs',     autoRate: true },
  { code: 'XCD', name: 'Dólar del Caribe Oriental',        symbol: '$',      autoRate: true },
  // ── Asia-Pacífico ─────────────────────────────────────────────────────────
  { code: 'BDT', name: 'Taka bangladesí',                  symbol: '৳',      autoRate: true },
  { code: 'BND', name: 'Dólar de Brunéi',                  symbol: '$',      autoRate: true },
  { code: 'BTN', name: 'Ngultrum butanés',                 symbol: 'Nu.',    autoRate: true },
  { code: 'CNH', name: 'Yuan chino (offshore)',            symbol: '¥',      autoRate: true },
  { code: 'CNY', name: 'Yuan chino',                       symbol: '¥',      autoRate: true },
  { code: 'FJD', name: 'Dólar fiyiano',                    symbol: '$',      autoRate: true },
  { code: 'HKD', name: 'Dólar de Hong Kong',               symbol: 'HK$',    autoRate: true },
  { code: 'IDR', name: 'Rupia indonesia',                  symbol: 'Rp',     autoRate: true },
  { code: 'INR', name: 'Rupia india',                      symbol: '₹',      autoRate: true },
  { code: 'KHR', name: 'Riel camboyano',                   symbol: '៛',      autoRate: true },
  { code: 'KPW', name: 'Won norcoreano',                   symbol: '₩',      autoRate: true },
  { code: 'KRW', name: 'Won surcoreano',                   symbol: '₩',      autoRate: true },
  { code: 'LAK', name: 'Kip laosiano',                     symbol: '₭',      autoRate: true },
  { code: 'LKR', name: 'Rupia de Sri Lanka',               symbol: '₨',      autoRate: true },
  { code: 'MMK', name: 'Kyat birmano',                     symbol: 'K',      autoRate: true },
  { code: 'MNT', name: 'Tögrög mongol',                    symbol: '₮',      autoRate: true },
  { code: 'MOP', name: 'Pataca macaense',                  symbol: 'P',      autoRate: true },
  { code: 'MVR', name: 'Rufiyaa maldiva',                  symbol: 'MVR',    autoRate: true },
  { code: 'MYR', name: 'Ringgit malayo',                   symbol: 'RM',     autoRate: true },
  { code: 'NPR', name: 'Rupia nepalesa',                   symbol: 'Rs.',    autoRate: true },
  { code: 'NZD', name: 'Dólar neozelandés',                symbol: 'NZ$',    autoRate: true },
  { code: 'PGK', name: 'Kina de Papúa Nueva Guinea',       symbol: 'K',      autoRate: true },
  { code: 'PHP', name: 'Peso filipino',                    symbol: '₱',      autoRate: true },
  { code: 'PKR', name: 'Rupia pakistaní',                  symbol: '₨',      autoRate: true },
  { code: 'SGD', name: 'Dólar de Singapur',                symbol: 'S$',     autoRate: true },
  { code: 'THB', name: 'Baht tailandés',                   symbol: '฿',      autoRate: true },
  { code: 'TWD', name: 'Dólar taiwanés',                   symbol: '$',      autoRate: true },
  { code: 'VND', name: 'Dong vietnamita',                  symbol: '₫',      autoRate: true },
  { code: 'WST', name: 'Tālā samoano',                     symbol: 'T',      autoRate: true },
  // ── Europa ────────────────────────────────────────────────────────────────
  { code: 'ALL', name: 'Lek albanés',                      symbol: 'L',      autoRate: true },
  { code: 'AMD', name: 'Dram armenio',                     symbol: '֏',      autoRate: true },
  { code: 'AZN', name: 'Manat azerbaiyano',                symbol: '₼',      autoRate: true },
  { code: 'BAM', name: 'Marco bosnio',                     symbol: 'КМ',     autoRate: true },
  { code: 'BYN', name: 'Rublo bielorruso',                 symbol: 'Br',     autoRate: true },
  { code: 'CZK', name: 'Corona checa',                     symbol: 'Kč',     autoRate: true },
  { code: 'DKK', name: 'Corona danesa',                    symbol: 'kr.',    autoRate: true },
  { code: 'GEL', name: 'Lari georgiano',                   symbol: '₾',      autoRate: true },
  { code: 'HUF', name: 'Forinto húngaro',                  symbol: 'Ft',     autoRate: true },
  { code: 'ISK', name: 'Corona islandesa',                 symbol: 'kr.',    autoRate: true },
  { code: 'MDL', name: 'Leu moldavo',                      symbol: 'L',      autoRate: true },
  { code: 'MKD', name: 'Denar macedonio',                  symbol: 'ден',    autoRate: true },
  { code: 'NOK', name: 'Corona noruega',                   symbol: 'kr',     autoRate: true },
  { code: 'PLN', name: 'Esloti polaco',                    symbol: 'zł',     autoRate: true },
  { code: 'RON', name: 'Leu rumano',                       symbol: 'Lei',    autoRate: true },
  { code: 'RSD', name: 'Dinar serbio',                     symbol: 'RSD',    autoRate: true },
  { code: 'RUB', name: 'Rublo ruso',                       symbol: '₽',      autoRate: true },
  { code: 'SEK', name: 'Corona sueca',                     symbol: 'kr',     autoRate: true },
  { code: 'TJS', name: 'Somoni tayiko',                    symbol: 'ЅМ',     autoRate: true },
  { code: 'TMT', name: 'Manat turcomano',                  symbol: 'm',      autoRate: true },
  { code: 'TRY', name: 'Lira turca',                       symbol: '₺',      autoRate: true },
  { code: 'UAH', name: 'Grivna ucraniana',                 symbol: '₴',      autoRate: true },
  { code: 'UZS', name: 'Som uzbeko',                       symbol: "so'm",   autoRate: true },
  // ── Medio Oriente ─────────────────────────────────────────────────────────
  { code: 'AED', name: 'Dírham emiratí',                   symbol: 'د.إ',    autoRate: true },
  { code: 'BHD', name: 'Dinar bareiní',                    symbol: 'د.ب',    autoRate: true },
  { code: 'ILS', name: 'Séquel israelí',                   symbol: '₪',      autoRate: true },
  { code: 'IQD', name: 'Dinar iraquí',                     symbol: 'ع.د',    autoRate: true },
  { code: 'IRR', name: 'Rial iraní',                       symbol: '﷼',      autoRate: true },
  { code: 'JOD', name: 'Dinar jordano',                    symbol: 'د.ا',    autoRate: true },
  { code: 'KWD', name: 'Dinar kuwaití',                    symbol: 'د.ك',    autoRate: true },
  { code: 'LBP', name: 'Libra libanesa',                   symbol: 'ل.ل',    autoRate: true },
  { code: 'OMR', name: 'Rial omaní',                       symbol: 'ر.ع.',   autoRate: true },
  { code: 'QAR', name: 'Riyal catarí',                     symbol: 'ر.ق',    autoRate: true },
  { code: 'SAR', name: 'Riyal saudí',                      symbol: 'ر.س',    autoRate: true },
  { code: 'SYP', name: 'Libra siria',                      symbol: '£S',     autoRate: true },
  { code: 'YER', name: 'Rial yemení',                      symbol: '﷼',      autoRate: true },
  // ── África ────────────────────────────────────────────────────────────────
  { code: 'DZD', name: 'Dinar argelino',                   symbol: 'د.ج',    autoRate: true },
  { code: 'EGP', name: 'Libra egipcia',                    symbol: 'ج.م',    autoRate: true },
  { code: 'ETB', name: 'Birr etíope',                      symbol: 'Br',     autoRate: true },
  { code: 'GHS', name: 'Cedi ghanés',                      symbol: '₵',      autoRate: true },
  { code: 'KES', name: 'Chelín keniano',                   symbol: 'KSh',    autoRate: true },
  { code: 'LYD', name: 'Dinar libio',                      symbol: 'ل.د',    autoRate: true },
  { code: 'MAD', name: 'Dírham marroquí',                  symbol: 'د.م.',   autoRate: true },
  { code: 'MGA', name: 'Ariary malgache',                  symbol: 'Ar',     autoRate: true },
  { code: 'MUR', name: 'Rupia mauriciana',                 symbol: '₨',      autoRate: true },
  { code: 'MWK', name: 'Kwacha malauí',                    symbol: 'MK',     autoRate: true },
  { code: 'MZN', name: 'Metical mozambiqueño',             symbol: 'MTn',    autoRate: true },
  { code: 'NAD', name: 'Dólar namibio',                    symbol: '$',      autoRate: true },
  { code: 'NGN', name: 'Naira nigeriana',                  symbol: '₦',      autoRate: true },
  { code: 'RWF', name: 'Franco ruandés',                   symbol: 'FRw',    autoRate: true },
  { code: 'SCR', name: 'Rupia de Seychelles',              symbol: '₨',      autoRate: true },
  { code: 'SDG', name: 'Libra sudanesa',                   symbol: '£',      autoRate: true },
  { code: 'SOS', name: 'Chelín somalí',                    symbol: 'Sh',     autoRate: true },
  { code: 'SSP', name: 'Libra sursudanesa',                symbol: '£',      autoRate: true },
  { code: 'TND', name: 'Dinar tunecino',                   symbol: 'د.ت',    autoRate: true },
  { code: 'TZS', name: 'Chelín tanzano',                   symbol: 'Sh',     autoRate: true },
  { code: 'UGX', name: 'Chelín ugandés',                   symbol: 'USh',    autoRate: true },
  { code: 'XAF', name: 'Franco CFA de África Central',     symbol: 'CFA',    autoRate: true },
  { code: 'XOF', name: 'Franco CFA de África Occidental',  symbol: 'Fr',     autoRate: true },
  { code: 'ZAR', name: 'Rand sudafricano',                 symbol: 'R',      autoRate: true },
  { code: 'ZMW', name: 'Kwacha zambiano',                  symbol: 'K',      autoRate: true },
  { code: 'ZWG', name: 'Zimbabwe Gold',                    symbol: 'ZiG',    autoRate: true },
  // ── Metales y otros ───────────────────────────────────────────────────────
  { code: 'XAU', name: 'Oro (onza troy)',                  symbol: 'oz t',   autoRate: true },
  { code: 'XAG', name: 'Plata (onza troy)',                symbol: 'oz t',   autoRate: true },
  { code: 'XPT', name: 'Platino (onza troy)',              symbol: 'oz t',   autoRate: true },
  { code: 'XPD', name: 'Paladio (onza troy)',              symbol: 'oz t',   autoRate: true },
  { code: 'XDR', name: 'Derechos Especiales de Giro (FMI)', symbol: 'SDR',  autoRate: true },
  { code: 'XPF', name: 'Franco CFP (Pacífico)',            symbol: 'Fr',     autoRate: true },
  // ── Otros ─────────────────────────────────────────────────────────────────
  { code: 'AFN', name: 'Afgani afgano',                    symbol: '؋',      autoRate: true },
  { code: 'ANG', name: 'Florín antillano neerlandés',      symbol: 'ƒ',      autoRate: true },
  { code: 'AOA', name: 'Kwanza angoleño',                  symbol: 'Kz',     autoRate: true },
  { code: 'AWG', name: 'Florín arubeño',                   symbol: 'ƒ',      autoRate: true },
  { code: 'BBD', name: 'Dólar de Barbados',                symbol: '$',      autoRate: true },
  { code: 'BIF', name: 'Franco burundés',                  symbol: 'Fr',     autoRate: true },
  { code: 'BMD', name: 'Dólar de Bermuda',                 symbol: '$',      autoRate: true },
  { code: 'BSD', name: 'Dólar bahameño',                   symbol: '$',      autoRate: true },
  { code: 'BWP', name: 'Pula botsuanesa',                  symbol: 'P',      autoRate: true },
  { code: 'CDF', name: 'Franco congoleño',                 symbol: 'Fr',     autoRate: true },
  { code: 'CVE', name: 'Escudo caboverdiano',              symbol: '$',      autoRate: true },
  { code: 'DJF', name: 'Franco yibutiano',                 symbol: 'Fdj',    autoRate: true },
  { code: 'ERN', name: 'Nakfa eritreo',                    symbol: 'Nfk',    autoRate: true },
  { code: 'FKP', name: 'Libra malvinense',                 symbol: '£',      autoRate: true },
  { code: 'GGP', name: 'Libra de Guernsey',                symbol: '£',      autoRate: true },
  { code: 'GIP', name: 'Libra gibraltareña',               symbol: '£',      autoRate: true },
  { code: 'GMD', name: 'Dalasi gambiano',                  symbol: 'D',      autoRate: true },
  { code: 'GNF', name: 'Franco guineano',                  symbol: 'Fr',     autoRate: true },
  { code: 'IMP', name: 'Libra manesa',                     symbol: '£',      autoRate: true },
  { code: 'JEP', name: 'Libra de Jersey',                  symbol: '£',      autoRate: true },
  { code: 'KGS', name: 'Som kirguís',                      symbol: 'som',    autoRate: true },
  { code: 'KMF', name: 'Franco comorense',                 symbol: 'Fr',     autoRate: true },
  { code: 'KYD', name: 'Dólar de Caimán',                  symbol: '$',      autoRate: true },
  { code: 'KZT', name: 'Tenge kazajo',                     symbol: '₸',      autoRate: true },
  { code: 'LRD', name: 'Dólar liberiano',                  symbol: '$',      autoRate: true },
  { code: 'LSL', name: 'Loti lesotense',                   symbol: 'L',      autoRate: true },
  { code: 'MRO', name: 'Uguiya mauritana (ant.)',          symbol: 'UM',     autoRate: true },
  { code: 'MRU', name: 'Uguiya mauritana',                 symbol: 'UM',     autoRate: true },
  { code: 'SBD', name: 'Dólar de las Salomón',             symbol: '$',      autoRate: true },
  { code: 'SHP', name: 'Libra de Santa Elena',             symbol: '£',      autoRate: true },
  { code: 'SLE', name: 'Leone de Sierra Leona',            symbol: 'Le',     autoRate: true },
  { code: 'STN', name: 'Dobra de Santo Tomé',              symbol: 'Db',     autoRate: true },
  { code: 'SZL', name: 'Lilangeni suazi',                  symbol: 'E',      autoRate: true },
  { code: 'TOP', name: "Pa'anga tongano",                  symbol: 'T$',     autoRate: true },
  { code: 'VUV', name: 'Vatu vanuatense',                  symbol: 'Vt',     autoRate: true },
  { code: 'XCG', name: 'Florín caribeño',                  symbol: 'Cg',     autoRate: true },
]

// ── Currency sort helpers ──────────────────────────────────────────────────────

const COMMON_CURRENCY_CODES = ['MXN', 'USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CHF']

/** Pure alphabetical by Spanish name — for onboarding and base-currency pickers */
export function getAlphabeticalCurrencies() {
  return [...SUPPORTED_CURRENCIES].sort((a, b) =>
    a.name.localeCompare(b.name, 'es')
  )
}

/**
 * Smart sort for transaction / account pickers:
 * preferred code first → common currencies (MXN, USD, EUR…) → rest A→Z
 */
export function getSmartSortedCurrencies(preferredCode?: string) {
  const sorted = [...SUPPORTED_CURRENCIES].sort((a, b) =>
    a.name.localeCompare(b.name, 'es')
  )
  const preferred = preferredCode
    ? sorted.filter(c => c.code === preferredCode)
    : []
  const common = sorted.filter(
    c => COMMON_CURRENCY_CODES.includes(c.code) && c.code !== preferredCode
  )
  const rest = sorted.filter(
    c => !COMMON_CURRENCY_CODES.includes(c.code) && c.code !== preferredCode
  )
  return [...preferred, ...common, ...rest]
}

// Shortcut iCloud share links
export const SHORTCUT_LINKS = {
  applePay: 'https://www.icloud.com/shortcuts/8ed8c9e88af8415e92ef6caebba4cb12',
  quickEntry: 'https://www.icloud.com/shortcuts/ceb9ed9baada4f5ebc77fc66af545e33',
}
